version: '2'
services:
    payara-full:
        build: .
        environment:
           - ADMIN_PASSWORD=admin
        ports:
            - "8080:8080"
            - "4848:4848"
        entrypoint:
            - /opt/payara41/bin/asadmin
            - start-domain
            - -v
        volumes:
          # application to deploy at startup
            - "./data/payara/deployments:/opt/payara41/deployments"
          # autodeploy (discouraged : no parameters, needs write access)
            - "./data/payara/autodeploy:/opt/payara41/glassfish/domains/domain1/autodeploy"

            - "./payara-init.sh:/usr/local/bin/payara-init.sh"
        depends_on:
            - db
    db:
        image: postgres:9.4
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: pnpc_password
            POSTGRES_USER: pnpc_app
            POSTGRES_DB: pnpc_app
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata
volumes:
    pgdata:
